alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists phone cascade
drop table if exists Student cascade
